apiVersion: v1
kind: Pod
metadata:
  name: speed-trainer
spec:
  # increase share memory for pytorch dataloader
  volumes:
    - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "4092Mi"
  volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
  containers:
  - name: trainer
    image: registry.mobilityservices.io/am/roam/realtime/speed-models/das:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 30Gi
        # ^ Set memory in case default limits are set low
        nvidia.com/gpu: 1 # requesting 1 GPU
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
  imagePullSecrets:
    - name: registry.mobilityservices.io

